version: "3.4"

x-default: &default
  build:
    context: .
    dockerfile: Dockerfile.development
  working_dir: /var/www/app
  links:
    - db
  volumes:
    - .:/var/www/app:cached
    - ./public/packs:/var/www/app/public/packs
    - ./vendor/bundle:/var/www/app/vendor/bundle
    - ./node_modules:/var/www/app/node_modules
    - ./tmp:/var/www/app/tmp
  environment:
    - EDITOR="vim"
    - DATABASE_HOST=db
    - REDIS_URL=redis://redis:6379/0
    - TZ=Asia/Tokyo
    - RAILS_SYSTEM_TESTING_SCREENSHOT=inline

services:
  app:
    <<: *default
    ports:
      - '3000:3000'
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bin/rails server -p 3000 -b 0.0.0.0"
    # command: /bin/sh -c "bundle exec rails new . --force --database=mysql --skip-bundle --skip-test --skip-turbolinks --skip-webpack-install --skip-action-cable --skip-active-storage"
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    ports:
      - '13306:3306'
    volumes:
      - ./docker_volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
